### ISSUE TITLE
scheduler.step(log_info[f"R@1"]) KeyError: 'R@1'

### ISSUE THREAD

**Issue by Samonsix** [MalongTech/research-xbm#8]
CUDA_VISIBLE_DEVICES=0 python3 tools/train_net.py --cfg configs/sample_config.yaml

Traceback (most recent call last):
  File "tools/train_net.py", line 81, in <module>
    train(cfg)
  File "tools/train_net.py", line 64, in train
    criterion, checkpointer, writer, device, checkpoint_period, arguments, logger,)
  File "/home/shengyang/work/hg-git/HS/research-xbm/ret_benchmark/engine/trainer.py", line 74, in do_train
    scheduler.step(log_info[f"R@1"])
KeyError: 'R@1'

torch: 1.4.0
GTX 1080ti

what's wrong with it?

**Comment by jingyang2017** [comment]
I meet the same problem, how did you solve it?

**Comment by NanAlbert** [comment]
It seems that replacing **scheduler.step(log_info[f"R@1"])** with **scheduler.step(log_info[f"e_precision_at_1"])** will work. It works to me.

**Comment by XinyiXuXD** [comment]
> It seems that replacing **scheduler.step(log_info[f"R@1"])** with **scheduler.step(log_info[f"e_precision_at_1"])** will work. It works to me.

I came across the same problem and your solution works for me too.  May I ask that can you reproduce the performance on the stanford_online_products dataset reported in the XBM paper?

**Comment by NanAlbert** [comment]
> > It seems that replacing **scheduler.step(log_info[f"R@1"])** with **scheduler.step(log_info[f"e_precision_at_1"])** will work. It works to me.
> 
> I came across the same problem and your solution works for me too. May I ask that can you reproduce the performance on the stanford_online_products dataset reported in the XBM paper?

I don’t remember the specific results. I just referred to the implementation part of the model and did not pay attention to the accuracy of this model.  Sorry for not being able to help you.
